services:
  database:
    image: postgres:15.3-bullseye
    container_name: nautilus-database
    restart: always
    volumes:
      - pg_data_nautilus:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nautilus
      - POSTGRES_PASSWORD=nautilus
      - POSTGRES_DB=nautilus
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U nautilus
      interval: 3s
      retries: 10
  redis:
    image: redis:7.2
    container_name: nautilus-redis
    restart: always
    volumes:
      - pg_data_redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 3s
      retries: 10
  backend:
    build: ../backend
    container_name: nautilus-backend
    volumes:
      - backend_storage:/storage
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - REDIS_URI=${REDIS_URI}
      - S3_URL_WITH_CREDENTIALS=${S3_URL_WITH_CREDENTIALS}
      - PRIVATE_SALT=secrectkey
      - ALLOWED_ORIGINS=http://localhost:8081|http://localhost:8082
      - TRANSIENT_STORAGE_PATH=/storage
      - CHANNEL_NAME=${CHANNEL_NAME}
      - RUN_DB_MIGRATIONS=y
    ports:
      - 8080:80
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    build: ../backend
    volumes:
      - backend_storage:/storage
    container_name: nautilus-backend-worker
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - REDIS_URI=${REDIS_URI}
      - S3_URL_WITH_CREDENTIALS=${S3_URL_WITH_CREDENTIALS}
      - PRIVATE_SALT=secrectkey
      - CHANNEL_NAME=${CHANNEL_NAME}
    command: ["rq-worker"]
    depends_on:
      - backend
  frontend:
    build: ../frontend
    container_name: nautilus-frontend
    ports:
      - 8081:80
    environment:
      - NAUTILUS_WEB_API=${NAUTILUS_WEB_API}
      - NAUTILUS_FILE_QUOTA=${NAUTILUS_FILE_QUOTA}
      - NAUTILUS_PROJECT_QUOTA=${NAUTILUS_PROJECT_QUOTA}
      - NAUTILUS_REFRESH_TIME=${NAUTILUS_REFRESH_TIME}
    depends_on:
      - backend
  frontend-dev:
    build:
      dockerfile: ../dev/frontend-tools/Dockerfile
      context: ../frontend
    container_name: nautilus-frontend-dev
    volumes:
      - ../frontend/public:/src/public
      - ../frontend/src:/src/src
    ports:
      - 8082:80
    environment:
      - NAUTILUS_WEB_API=http://localhost:8083/v1
      - NAUTILUS_FILE_QUOTA=${NAUTILUS_FILE_QUOTA}
      - NAUTILUS_PROJECT_QUOTA=${NAUTILUS_PROJECT_QUOTA}
      - NAUTILUS_REFRESH_TIME=${NAUTILUS_REFRESH_TIME}
    depends_on:
      - backend
  backend-dev:
    build:
      dockerfile: ../dev/backend-tools-tests/Dockerfile
      context: ../backend
    volumes:
      - backend_storage:/storage
      - ../backend:/app
    container_name: nautilus-backend-dev
    entrypoint: ''
    command: fastapi dev --host 0.0.0.0 --port 80 api/entrypoint.py
    ports:
      - 8083:80
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - REDIS_URI=${REDIS_URI}
      - S3_URL_WITH_CREDENTIALS=${S3_URL_WITH_CREDENTIALS}
      - PRIVATE_SALT=secrectkey
      - TRANSIENT_STORAGE_PATH=/storage
      - CHANNEL_NAME=${CHANNEL_NAME}
      - ALLOWED_ORIGINS=http://localhost:8081|http://localhost:8082
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  backend-tools:
    build:
      dockerfile: ../dev/backend-tools-tests/Dockerfile
      context: ../backend
    volumes:
      - backend_storage:/storage
    container_name: nautilus-backend-tools
    command: /bin/sh -c "sleep Infinity"
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - REDIS_URI=${REDIS_URI}
      - S3_URL_WITH_CREDENTIALS=${S3_URL_WITH_CREDENTIALS}
      - PRIVATE_SALT=secrectkey
      - TRANSIENT_STORAGE_PATH=/storage
      - CHANNEL_NAME=${CHANNEL_NAME}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  backend-tests:
    build:
      dockerfile: ../dev/backend-tools-tests/Dockerfile
      context: ../backend
    volumes:
      - backend_storage:/storage
    container_name: nautilus-backend-tests
    command: /bin/sh -c "sleep Infinity"
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - REDIS_URI=${REDIS_URI}
      - S3_URL_WITH_CREDENTIALS=${S3_URL_WITH_CREDENTIALS}
      - PRIVATE_SALT=secrectkey
      - TRANSIENT_STORAGE_PATH=/storage
      - CHANNEL_NAME=${CHANNEL_NAME}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  pg_data_nautilus:
  pg_data_redis:
  backend_storage:
