name: QA-Frontend

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]

jobs:
  check-frontend-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.nvmrc'
          architecture: x64

      - name: Install dependencies (and project)
        working-directory: frontend
        run: |
          corepack enable
          yarn cache clean
          yarn install

      - name: Check format
        working-directory: frontend
        run: yarn run format:check

      - name: Check eslint
        working-directory: frontend
        run: yarn run lint:check
