name: QA

on: [push, pull_request]

jobs:
  check-qa:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Setup dependencies.
        working-directory: backend
        run: |
          pip install --upgrade pipenv
          pipenv sync --dev

      - name: Check black formatting
        working-directory: backend
        run: pipenv run invoke check-black

      - name: Check import order with isort
        working-directory: backend
        run: pipenv run invoke check-isort
