name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python: [ "3.11" ]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:15.3-bullseye
        env:
          POSTGRES_PASSWORD: nautilus
          POSTGRES_DB: nautilus
          POSTGRES_PORT: 5432
          POSTGRES_USER: nautilus
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          cache: 'pip'

      - name: Install dependencies (and project)
        working-directory: backend
        run: |
          pip install -U pip
          pip install -e .[test,scripts]

      - name: Initialize the database
        working-directory: backend/src
        env:
          POSTGRES_URI: "postgresql+psycopg://nautilus:nautilus@localhost:5432/nautilus"
        run: alembic upgrade head

      - name: Run the tests
        working-directory: backend
        env:
          POSTGRES_URI: "postgresql+psycopg://nautilus:nautilus@localhost:5432/nautilus"
        run: inv coverage --args "-vvv"

      - name: Upload coverage to Codecov
        if: matrix.python == '3.11'
        uses: codecov/codecov-action@v3
        with:
          working-directory: backend
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Ensure we can build targets
        if: matrix.python == '3.11'
        working-directory: backend
        run: |
          pip install build
          python3 -m build
